camera0: /dev/video0
camera1: /dev/video2
frame_width: 1920
frame_height: 1080
mono_calibration_frames: 50
stereo_calibration_frames: 50
view_resize: 1
checkerboard_box_size_scale : 2.00
checkerboard_rows: 5
checkerboard_columns: 6
cooldown: 200
